apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuln-fileupload
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vuln-fileupload
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vuln-fileupload
    spec:
      serviceAccountName: developer-steve
      containers:
      - name: vuln-fileupload
        image: biltisberger/vuln-fileupload:latest
        ports:
        - containerPort: 1338
          protocol: TCP
