apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuln-ping
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vuln-ping
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vuln-ping
    spec:
      serviceAccountName: developer-steve
      containers:
      - name: vuln-ping
        image: biltisberger/vuln-ping:latest
        ports:
        - containerPort: 1338
          protocol: TCP
