apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer-steve
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: developer-steve-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "list"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-steve-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: developer-steve
  namespace: default
roleRef:
  kind: Role
  name: developer-steve
  apiGroup: rbac.authorization.k8s.io
