apiVersion: v1
kind: Service
metadata:
  annotations:
  name: vuln-fileupload
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: vuln-fileupload
