apiVersion: v1
kind: Service
metadata:
  annotations:
  name: vuln-ping
spec:
  ports:
  - name: http
    port: 1338
    protocol: TCP
    targetPort: 1338
  selector:
    app.kubernetes.io/name: vuln-ping
